apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: launch-pgscalc-webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    calculate:
      port: "12000"
      endpoint: /calculate
      method: POST
