apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: launch-pgscalc
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: launch-pgscalc-webhook
    eventName: calculate
  triggers:
  - template:
      name: payload
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: payload-
              labels:
                app: payload
            spec:
              restartPolicy: Never
              volumes:
                - name: vol-1
                  persistentVolumeClaim:
                    claimName: nfsclaim
              containers:
              - name: nextflow-driver
                image: docker.io/nextflow/nextflow:21.10.6                
                command: ["nextflow"]
                args: ["run", "pgscatalog/pgsc_calc", "-r", "master", "-profile", "test,k8s", "--input", "/workspace/data/samplesheet.csv", "--scorefile", "/workspace/data/PGS001229_22.txt", "-w", "/workspace/work"]  
                volumeMounts:
                  - name: vol-1
                    mountPath: "/workspace"
                env:
                  - name: NXF_EXECUTOR
                    value: k8s
                  - name: NXF_HOME
                    value: /workspace/nextflow
              resources:
                requests:
                  cpu: 2
                  memory: 2G
                limits:
                  cpu: 2
                  memory: 3G                  
 
