apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: launch-pgscalc-kafka
spec:
  kafka:
    calculate:
      url: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      topic: pipeline-launch
      jsonBody: true
      partition: "0"
