apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: launch-pgscalc-kafka
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: launch-pgscalc-kafka
    eventName: calculate
  triggers:
  - template:
      name: kafka-pgscalc-trigger
      k8s:
        operation: create
        source:
          git: 
            url: "https://github.com/ebi-gdp/pgsc-calc-events"           
            filePath: "calculate/pgsc-pod.yaml"
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.params
            dest: spec.containers.0.env.0.value
          - src:
              dependencyName: payload
              dataKey: body.nxf_work
            dest: spec.containers.0.env.1.value
          - src:
              dependencyName: payload
              dataKey: body.id
            dest: spec.containers.0.env.2.value



