apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-deploy-pod-role
  namespace: test
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-role-binding
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-deploy-pod-role
subjects:
- kind: ServiceAccount
  name: argo-events-sa
  namespace: test
