apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: pgscalc-log-error
spec:
  dependencies:
    - name: error-dep
      eventSourceName: pgscalc-log-webhook
      eventName: log
      filters:
        data:
          - path: body.event
            type: string
            value:
              - "^error"
  triggers:
  - template:
      name: error-trigger
      kafka:
        url: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        topic: pipeline-status
        partition: 0
        payload:
            - src:
                dependencyName: error-dep
                dataKey: body.event
              dest: status
            - src:
                dependencyName: error-dep
                dataKey: body.runName
              dest: uid
            - src:
                dependencyName: error-dep
                dataKey: body.utcTime
              dest: time
            - src:
                dependencyName: error-dep
                dataKey: body.meta
              dest: meta              
