apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: pgscalc-log-webhook
spec:
  service:
    ports:
      - port: 4567
        targetPort: 4567
  webhook:
    log:
      port: "4567"
      endpoint: /log
      method: POST
