apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: pgscalc-log
spec:
  dependencies:
    - name: test-log
      eventSourceName: pgscalc-log-webhook
      eventName: log
  triggers:
  - template:
      name: kafka-trigger
      kafka:
        url: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        topic: my-topic
        partition: 0
        payload:
            - src:
                dependencyName: test-log
                dataKey: body.event
              dest: event
            - src:
                dependencyName: test-log
                dataKey: body.runName
              dest: id
            - src:
                dependencyName: test-log
                dataKey: body.utcTime
              dest: utcTime
            - src:
                dependencyName: test-log
                dataKey: body.runId
              dest: runId
            - src:
                dependencyName: test-log
                dataKey: body.metadata
              dest: metadata          

