apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: pgscalc-log
spec:
  dependencies:
    - name: payload
      eventSourceName: pgscalc-log-webhook
      eventName: log
      transform:
        jq: ".body.runName, .body.event, .body.utcTime, .body.runId"
      filters:
        data:
          - path: body.event
            type: string
            value:
              - "started"
              - "completed"
              - "error"
  triggers:
  - template:
      conditions: "payload"
      name: log-trigger
      log: {}        

