apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: pgscalc-log
spec:
  dependencies:
    - name: test-log
      eventSourceName: pgscalc-log-webhook
      eventName: log
      filters:
        data:
          - path: body.event
            type: string
            value:
              - "^started"
              - "^completed"
              - "^error"
  triggers:
  - template:
      name: kafka-trigger
      kafka:
        url: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        topic: pipeline-status
        partition: 0
        payload:
            - src:
                dependencyName: test-log
                dataKey: body.event
              dest: status
            - src:
                dependencyName: test-log
                dataKey: body.runName
              dest: uid
            - src:
                dependencyName: test-log
                dataKey: body.utcTime
              dest: time
            - src:
                dependencyName: test-log
                dataKey: body.metadata.parameters.outdir
              dest: outdir

