apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: launch-pgscalc
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: launch-pgscalc-webhook
    eventName: calculate
  triggers:
  - template:
      name: webhook-pgscalc-trigger
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: pgscalc-
              labels:
                app: nextflow
            spec:
              restartPolicy: Never
              volumes:
                - name: vol-1
                  persistentVolumeClaim:
                    claimName: nfsclaim
              containers:
                - name: nextflow-driver
                  image: docker.io/nextflow/nextflow:21.10.6
                  command: ["/bin/sh","-c"]
                  # TODO: containerise the pipeline to avoid cloning so much
                  args: ["/bin/echo \"${JSON}\" > /tmp/params.json; cat /tmp/params.json; nextflow run pgscatalog/pgsc_calc -name ${ID} -latest -profile k8s -params-file /tmp/params.json"]
                  volumeMounts:
                    - name: vol-1
                      mountPath: "/workspace"
                  env:
                    - name: JSON
                      value: "REPLACED"
                    - name: NXF_WORK
                      value: "REPLACED"
                    - name: ID
                      value: "REPLACED"
                    - name: NXF_ANSI_LOG
                      value: "false"
                    - name: NXF_HOME
                      value: /workspace/nxf_home
                    - name: NXF_EXECUTOR
                      value: k8s
                  resources:
                    requests:
                      cpu: 2
                      memory: 2G
                    limits:
                      cpu: 2
                      memory: 3G
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.params
            dest: spec.containers.0.env.0.value
          - src:
              dependencyName: payload
              dataKey: body.nxf_work
              value: /workspace/work
            dest: spec.containers.0.env.1.value
          - src:
              dependencyName: payload
              dataKey: body.id
              value: /workspace/work
            dest: spec.containers.0.env.2.value



