apiVersion: v1
kind: Pod
metadata:
  generateName: pgscalc-
  labels:
    app: nextflow
spec:
  containers:
    - args:
        - >-
          /bin/echo "${JSON}" > /tmp/params.json; cat /tmp/params.json; nextflow
          run pgscatalog/pgsc_calc -name ${ID} -latest -profile k8s -params-file
          /tmp/params.json -with-weblog
          http://pgscalc-log-webhook-eventsource-svc:4567
      command:
        - /bin/sh
        - '-c'
      env:
        - name: JSON
          value: REPLACED
        - name: NXF_WORK
          value: REPLACED
        - name: ID
          value: REPLACED
        - name: NXF_ANSI_LOG
          value: 'false'
        - name: NXF_HOME
          value: /workspace/nxf_home
        - name: NXF_EXECUTOR
          value: k8s
      image: 'docker.io/nextflow/nextflow:21.10.6'
      name: nextflow-driver
      resources:
        limits:
          cpu: 2
          memory: 3G
        requests:
          cpu: 2
          memory: 2G
      volumeMounts:
        - mountPath: /workspace
          name: vol-1
  restartPolicy: Never
  volumes:
    - name: vol-1
      persistentVolumeClaim:
        claimName: nfsclaim

